#!/usr/bin/env python3
"""Generate qemu/src/windows.rs from the model A validation split.

Week 6, D2: the QEMU firmware and the host reference must classify the
*same* bits. Both sides include the generated file verbatim, so the decimal
literals from the CSV are parsed to f32 by the same correctly-rounded rustc
parser on both sides — the fixed windows are bit-identical by construction.

Selection rule (deterministic): the first row of each class label 0..3.

Usage:
    python3 scripts/gen-qemu-windows.py            # ml/models/model_a.val.csv
    python3 scripts/gen-qemu-windows.py OTHER.csv
"""

from pathlib import Path
import sys

REPO = Path(__file__).resolve().parent.parent
DEFAULT_CSV = REPO / "ml/models/model_a.val.csv"
OUT = REPO / "qemu/src/windows.rs"

HEADER = """\
//! Fixed node-A windows for the QEMU demo and the host/QEMU parity check.
//!
//! GENERATED by scripts/gen-qemu-windows.py from {source} (the first row
//! of each class) — do not edit by hand; rerun the script instead.
//! Included verbatim by the firmware (qemu/src/main.rs) and by the host
//! reference (nodes/examples/qemu_host_ref.rs) — one source of bits.

// Recorded signal samples, not mathematical constants: a value may
// coincidentally sit near a known constant (clippy::approx_constant).
#![allow(clippy::approx_constant)]

/// A labelled fixed window (128 current samples, node A).
pub struct FixedWindow {{
    /// Ground-truth class index (0=idle, 1=run, 2=jam, 3=overload).
    pub label: u8,
    /// Raw window samples, A (model A input, `WindowSpec(A)` = 128 @ 1.6 kHz).
    pub samples: [f32; {n}],
}}

/// The fixed windows, one per class, in class order.
// Generated data — rustfmt must not rewrap the sample literals.
#[rustfmt::skip]
pub const WINDOWS: [FixedWindow; {count}] = [
"""


def main() -> int:
    csv_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CSV
    rows = csv_path.read_text().splitlines()
    header = rows[0].split(",")
    assert header[0] == "label", f"unexpected first column: {header[0]}"
    n = len(header) - 1

    picked: dict[int, list[str]] = {}
    for row in rows[1:]:
        if not row.strip():
            continue
        cells = row.split(",")
        label = int(cells[0])
        if label not in picked:
            picked[label] = cells[1:]

    lines = [
        HEADER.format(source=csv_path.name, n=n, count=len(picked)),
    ]
    for label in sorted(picked):
        cells = picked[label]
        lines.append(
            "    FixedWindow {\n"
            f"        label: {label},\n"
            f"        samples: [{', '.join(cells)}],\n"
            "    },\n"
        )
    lines.append("];\n")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(lines))
    print(f"{OUT}: {len(picked)} windows x {n} samples (labels {sorted(picked)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
