//! Golden features (week 3, D4): Rust `features-cli` vs numpy — feature parity
//! as a safety net (plan section 6).
//!
//! - integer features (zero-crossings): bit-for-bit;
//! - float features (RMS, peak, spectrum): ±1e-6.
//!
//! The fixture (`tests/golden/features.txt`) is generated by
//! `ml/scripts/golden_features.py` with system python3 + numpy; the window is
//! shared verbatim (9 significant digits round-trip float32 exactly), so both
//! sides compute features over identical inputs.

use std::fs;

use features_cli::features::{self, Features};

const FIXTURE: &str = "tests/golden/features.txt";
const FS: u32 = 1600;

struct Fixture {
    window: Vec<f32>,
    features: Features,
}

fn parse_fixture(text: &str) -> Option<Fixture> {
    let mut window = Vec::new();
    let mut parsed = Features {
        rms: 0.0,
        peak: 0.0,
        zero_crossings: 0,
        spectrum: [0.0; 3],
    };
    let mut section = "";
    for line in text.lines().map(str::trim) {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        match line {
            "window" => {
                section = "window";
                continue;
            }
            "features" => {
                section = "features";
                continue;
            }
            _ => {}
        }
        let (key, value) = match line.split_once(' ') {
            Some(pair) => pair,
            // Bare number lines are window samples.
            None => {
                if section == "window" {
                    window.push(line.parse().ok()?);
                    continue;
                }
                return None;
            }
        };
        match key {
            "rms" => parsed.rms = value.parse().ok()?,
            "peak" => parsed.peak = value.parse().ok()?,
            "zero_crossings" => parsed.zero_crossings = value.parse().ok()?,
            "spectrum[0]" => parsed.spectrum[0] = value.parse().ok()?,
            "spectrum[1]" => parsed.spectrum[1] = value.parse().ok()?,
            "spectrum[2]" => parsed.spectrum[2] = value.parse().ok()?,
            _ => return None,
        }
    }
    Some(Fixture {
        window,
        features: parsed,
    })
}

#[test]
fn features_match_numpy() {
    let text = fs::read_to_string(FIXTURE).unwrap_or_else(|error| {
        panic!("missing {FIXTURE} ({error}); run ml/scripts/golden_features.py")
    });
    let fixture = parse_fixture(&text).unwrap_or_else(|| panic!("could not parse {FIXTURE}"));
    assert_eq!(
        fixture.window.len(),
        128,
        "the window must match WindowSpec(A)"
    );

    let computed = features::extract(&fixture.window, FS);

    // Integer features: bit-for-bit (plan section 6, D4).
    assert_eq!(
        computed.zero_crossings, fixture.features.zero_crossings,
        "zero-crossings differ from numpy"
    );

    // Float features: ±1e-6.
    let close = |name: &str, got: f32, expected: f32| {
        assert!(
            (got - expected).abs() <= 1e-6,
            "{name}: {got} vs numpy {expected} (diff {} > 1e-6)",
            (got - expected).abs()
        );
    };
    close("rms", computed.rms, fixture.features.rms);
    close("peak", computed.peak, fixture.features.peak);
    for (bin, (got, expected)) in computed
        .spectrum
        .iter()
        .zip(fixture.features.spectrum)
        .enumerate()
    {
        close(&format!("spectrum[{bin}]"), *got, expected);
    }
}
